# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

on:
    release:
        types: [published]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - run: npm install

            # Update version based on release tag
            - run: |
                  VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
                  echo "Extracted version: $VERSION"
                  npm version "$VERSION" --no-git-tag-version

            # Use actions-js/push for git operations
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  message: 'Release version ${{ github.event.release.tag_name }}'
                  branch: main
                  rebase: true

            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
